### ISSUE TITLE
get_dependents() doesnt update due to precompilation

### ISSUE THREAD

**Issue by IanButterworth** [arnavs/PkgUtils.jl#3]
This line should probably be in an `__init__()` to allow any updates to the registry to be seen, otherwise the result gets locked by precompilation

https://github.com/arnavs/PkgUtils.jl/blob/1ee054b966228d29249db9ee3387fee074d03f76/src/dependencies.jl#L104

Nice function, btw!

**Comment by arnavs** [comment]
Thanks bro. Will fix.
